name: KiwiAdmin
main: com.yottabyte.bukkit.KiwiAdmin
version: 1.1
website: http://kiwike.se
author: yottabyte
description: >
             Admin plugin for Bukkit, adds important functions like kicking and banning.
commands:
  kick:
    description: Kick a player
    usage: /<command> player [reason] - Kick a player
  ban:
    description: Ban a player
    usage: /<command> player [reason] - Ban a player
  unban:
    description: Unban a player
    usage: /<command> player - Unban a player
  reloadka:
    description: Reload the banlist
    usage: /<command> - Reload KiwiAdmin
           
           